language: generic
sudo: require
services:
  - docker


before_install:
  - docker build -t sdhallam/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true sdhallam/docker-react npm run test
